services:
- type: web
  name: line-bot-python-flask
  env: python
  repo: https://github.com/bill8345/line-bot/tree/main.git
  buildCommand: cd examples/flask-echo;pip install gunicorn -r requirements.txt
  startCommand: cd examples/flask-echo;gunicorn app:app
  plan: free
  autoDeploy: false
  envVars:
  - key: fuuoYf9qSR4/IZRBtOlzzoeM0wIFjpj+M/DTxRRcAkCyzGgvXvjyBCAQiCa6qNt3R9IE6FIeoA+1WL1EoNsXq5/+UUuYFKQUJUxoZ82+mD15p55NMc2ry76U9rjyqWw9SC58ja2/TtxCdTV3+pb4DwdB04t89/1O/w1cDnyilFU=
    sync: false
  - key: 57909b02f6af9b63af74b5ee32c43d08
    sync: false
# - type: web
#   name: line-bot-python-flask-with-handler
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/flask-echo;pip install gunicorn -r requirements.txt
#   startCommand: cd examples/flask-echo;gunicorn app_with_handler:app
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-flask-kitchensink
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/flask-kitchensink;pip install gunicorn -r requirements.txt
#   startCommand: cd examples/flask-kitchensink;gunicorn app:app
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-simple-server
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/simple-server-echo;pip install -r requirements.txt
#   startCommand: cd examples/simple-server-echo;python app.py
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-aiohttp
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/aiohttp-echo;pip install -r requirements.txt
#   startCommand: cd examples/aiohttp-echo;python app.py
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
